workflows:
  react-native-ios:
    name: React Native iOS
    environment:
      vars:
        XCODE_WORKSPACE: "ios/ReactInMobile.xcodeproj"
        XCODE_SCHEME: "ReactInMobile"
      node: latest
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build ios
        script: |
          npx react-native run-ios --configuration Release
      - name: Xcode build (archive)
        script: |
          xcodebuild archive -workspace $XCODE_WORKSPACE -scheme $XCODE_SCHEME -sdk iphoneos -configuration Release -archivePath $CM_BUILD_DIR/ios.xcarchive
      - name: Xcode export archive
        script: |
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/ios.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $CM_BUILD_DIR/output
    artifacts:
      - build/ios/ipa/*.ipa
